name: schedule_update

on:
  push:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: true
        fetch-depth: 0
    - name: Create local changes
      run: |
        echo `date` >> a.time
    - name: Commit files
      run: |
        git config --local user.email "jiayi@iscas.ac.cn"
        git config --local user.name "Github_Action[bot]"
        git add a.time
        git commit -m "Update Files"
    - name: Push changes
      uses: summer-ospp/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

